name: Test coverage
on: 
  push:
jobs:
  codecov:
    name: codecov
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        uses: actions/setup-go@v2-beta
        with:
          go-version: '^1.14.0'
      -
        name: Generate coverage report
        run: go test ./... -coverprofile=coverage.txt -covermode=atomic
      -
        name: Upload coverage report
        uses: codecov/codecov-action@v1.0.6
        with:
          file: ./coverage.txt
          flags: unittests
